### ISSUE TITLE
Autocompletion?

### ISSUE THREAD

**Issue by pyros2097** [manastech/sublime-crystal#10]
Is it possible to add auto completion like [GoSublime](https://github.com/DisposaBoy/GoSublime) since it is a compiled language?
Or do we need a daemon like gocode? And something for formatting would also be good like gofmt.

**Comment by waj** [comment]
It might be possible although I think it would be much more complicated due to the global type inference. A daemon might be required, running the actual Crystal parser and type inference.
One challenge to solve would be what to show on a given context, because remember each method can be instantiated many times with different type arguments. Also, if a method is never used it wouldn't have any type information.

**Comment by pyros2097** [comment]
Just found this tool [Rsense](https://github.com/rsense/rsense) if we can create a server/daemon which conforms to that api, we can directly use their completion plugin code to have autocomplete for crystal. I was thinking of an easier approach by generating snippets(like `Http:Response.body    String|Nil`) just for all std classes but that might just be a wrong way to do this

**Comment by bararchy** [comment]
@pyros2097 Sorry for resurrecting this, but you can use https://github.com/TechMagister/cracker if still relevant

**Comment by RX14** [comment]
There's also https://github.com/crystal-lang-tools/scry, if sublime has a generic language server protocol extension.

**Comment by pyros2097** [comment]
@bararchy Thanks for the link. Will be experimenting on crystal lang again soon.
